# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Main CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check-frontend:
    name: 'Check Frontend'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: cd react-client
    - run: npm install
    - run: npm run tsc
    - run: npm run lint

  build-frontend:
    name: 'Build Frontend Artifact'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: cd react-client
    - run: npm install
    - run: npm run build
    - uses: actions/upload-artifact@v2
      with:
        name: public
        path: build/

  check-backend:
    name: 'Check Backend'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: cd server
    - run: npm install
    - run: npm run tsc
    - run: npm run lint

