# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Main CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check-frontend:
    name: 'Check Frontend'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
      working-directory: react-client
    - run: npm run tsc
      working-directory: react-client
    - run: npm run lint
      working-directory: react-client

  build-frontend:
    name: 'Build Frontend Artifact'
    needs: [check-frontend]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
      working-directory: react-client
    - run: npm run build
      working-directory: react-client
    - uses: actions/upload-artifact@v2
      with:
        name: public
        path: react-client/build/

  check-backend:
    name: 'Check Backend'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
      working-directory: server
    - run: npm run tsc
      working-directory: server
    - run: npm run lint
      working-directory: server

  Deploy:
    name: 'Deploy to Heroku'
    needs: [check-backend, build-frontend]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: public
        path: server/public
    - uses: akhileshns/heroku-deploy@v3.4.6
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "adventure-capitalist-clone-dem"
        heroku_email: "catrielmuller@gmail.com"
        usedocker: true
        appdir: server

